# Setup
title:        keep it simple
tagline:      ""
baseurl:      ""
paginate:     1
locale:       "jp"

plugins:
  - jekyll-paginate

# About/contact
author:
  name:       kbysta1
  url:        https://github.com/kbysta1

# Gems

#Others
markdown: kramdown

collections:
  sixpad:
    output: true

title-sixpad: シックスパッド(SIXPAD)でビール腹を解消できるか
tagline-sixpad: "運動が苦手でジムも続かなかったITエンジニアが、シックスパッドで楽して痩せられるのか検証しています"
